check:
  - thoth-build
build:
  base-image: quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.33.0
  build-stratergy: Source
  registry: quay.io
  registry-org: thoth-station
  registry-project: advise-reporter
  registry-secret: thoth-station-thoth-pusher-secret
deploy:
  project-org: "thoth-station"
  project-name: "thoth-application"
  image-name: "advise-reporter"
  overlay-contextpath: "advise-reporter/overlays/test/imagestreamtag.yaml"
